letter_scores = {"a": 1116, "b": 505, "c": 665, "d": 660, "e": 1417, "f": 264, "g": 241, "h": 315, "i": 675, "j": 20,
                 "k": 217, "l": 698, "m": 279, "n": 534, "o": 827, "p": 299, "q": 14, "r": 851, "s": 1166, "t": 663,
                 "u": 396, "v": 134, "w": 163, "x": 57, "y": 284, "z": 39}
words = ["arose", "earls", "laser", "arise", "raise", "aloes", "acres", "cares", "races", "scare", "aster", "rates",
         "tears", "dares", "dears", "reads", "earns", "aisle", "scale", "aeons", "least", "slate", "steal", "tales",
         "dales", "deals", "leads", "bares", "baser", "bears", "aides", "aside", "ideas", "caste", "cased", "dates",
         "roles", "lanes", "cores", "score", "store", "doers", "anise", "bales", "blase", "canes", "deans", "adore",
         "abets", "baste", "beast", "beats", "betas", "share", "based", "beads", "spare", "years", "fares", "fears",
         "safer", "gears", "cries", "close", "coles", "tires", "tries", "stole", "dries", "rides", "doles", "asker",
         "bores", "crest", "cause", "sauce", "clear", "alert", "alter", "eidos", "later", "alder", "banes", "beans",
         "codes", "coeds", "dotes", "aider", "aired", "swear", "wears", "carte", "cater", "crate", "react", "trace",
         "cadre", "cared", "cedar", "dater", "rated", "trade", "avers", "aches", "chase", "hates", "males", "meals",
         "heads", "shade", "capes", "space", "fleas", "paste", "tapes", "solar", "euros", "yeast", "resin", "rinse",
         "risen", "mates", "meats", "steam", "teams", "dames", "cafes", "faces", "fates", "feast", "feats", "fades",
         "slice", "roads", "eosin", "noise", "tiles", "delis", "learn", "renal", "slide", "aegis", "lakes", "leaks",
         "boles", "celts", "cones", "notes", "onset", "stone", "tones", "cages", "nodes", "gates", "stage", "abuse",
         "beaus", "alone", "anole", "baler", "blare", "cites", "crane", "dices", "cakes", "deist", "diets", "edits",
         "stake", "steak", "takes", "asked", "horse", "shore", "bodes", "ailed", "ideal", "pores", "ropes", "canoe",
         "cleat", "eclat", "ocean", "atone", "clade", "decal", "anode", "brace", "caber", "dealt", "delta", "easer",
         "erase", "arses", "areas", "bared", "beard", "bread", "ashen", "aspen", "slave", "rules", "abode", "adobe",
         "sweat", "waste", "acted", "cadet", "means", "names", "opera", "arils", "rails", "caves", "cruse", "cures",
         "curse", "arson", "saved", "lines", "beams", "afore", "coals", "colas", "astir", "altos", "loads", "douse",
         "boars", "biles", "carts", "cards", "since", "darts", "axels", "axles", "older", "dines", "snake", "sneak",
         "belts", "bones", "cents", "scent", "adios", "alien", "dents", "tends", "ascot", "coast", "coats", "codas",
         "clean", "bites", "eland", "worse", "bides", "holes", "bakes", "beaks", "coder", "cored", "credo", "decor",
         "taxes", "debts", "poles", "slope", "cable", "bleat", "table", "adzes", "easel", "lease", "sales", "seals",
         "baled", "blade", "enact", "pause", "caned", "dance", "chose", "echos", "emirs", "ethos", "those", "pearl",
         "tyres", "dyers", "terms", "amuse", "copes", "copse", "scope", "abide", "fires", "fries", "dopes", "posed",
         "early", "layer", "relay", "cease", "cases", "nurse", "reach", "asset", "seats", "state", "taste", "earth",
         "heart", "bated", "realm", "eased", "heard", "comes", "demos", "domes", "modes", "caper", "crape", "apter",
         "feral", "flare", "drape", "clues", "loans", "salon", "aimer", "duels", "dulse", "usage", "dregs", "trans",
         "cream", "deary", "ready", "darns", "enrol", "afire", "armed", "dream", "feria", "large", "suite", "dials",
         "facer", "farce", "phase", "shape", "bolas", "after", "doges", "fader", "fared", "cameo", "carbs", "crabs",
         "duets", "brats", "bards", "brads", "drabs", "crone", "shame", "cokes", "grace", "drone", "great", "bents",
         "grade", "acids", "bends", "adits", "boast", "boats", "wires", "cider", "cried", "creak", "tired", "tried",
         "adieu", "crews", "screw", "roses", "drake", "bored", "acute", "piles", "herbs", "jeans", "opens", "slept",
         "loves", "solve", "pages", "miles", "smile", "dowse", "ferns", "shake", "style", "chest", "byres", "epics",
         "spice", "files", "flies", "spite", "games", "berms", "peaks", "speak", "clefs", "water", "coves", "felts",
         "dewar", "stove", "votes", "bases", "abase", "babes", "doves", "lords", "emits", "items", "times", "deism",
         "dimes", "makes", "place", "plate", "pedal", "nails", "email", "carve", "caver", "crave", "blues", "avert",
         "bergs", "fakes", "clans", "cheat", "teach", "tunes", "camel", "delay", "liner", "lands", "ached", "dunes",
         "likes", "metal", "barns", "brans", "death", "hated", "medal", "cords", "amber", "autos", "bream", "bails",
         "basil", "fecal", "anger", "range", "fetal", "caped", "carol", "coral", "adept", "antis", "outer", "route",
         "satin", "stain", "cubes", "blast", "agile", "aimed", "amide", "media", "tubes", "bused", "decay", "nicer",
         "clone", "relax", "stand", "diner", "dikes", "boner", "borne", "ratio", "barge", "purse", "radio", "super",
         "basic", "baits", "decks", "facet", "trend", "alike", "hairs", "actor", "decaf", "faced", "house", "fated",
         "chars", "crash", "biter", "trash", "tribe", "rises", "dozes", "serum", "loses", "loose", "bride", "pairs",
         "shine", "baker", "brake", "break", "extra", "coned", "wages", "brews", "noted", "cress", "caged", "reset",
         "steer", "trees", "azole", "beaut", "carps", "craps", "faves", "scrap", "parts", "strap", "traps", "deers",
         "dress", "penis", "spine", "evils", "lives", "chaos", "craze", "mouse", "areal", "scary", "artsy", "cited",
         "edict", "askew", "spent", "crams", "drays", "yards", "spend", "caked", "chore", "smart", "capos", "other",
         "drams", "fairs", "mines", "surge", "doses", "dosed", "panel", "plane", "scarf", "farts", "aerie", "fines",
         "comas", "dives", "atoms", "areca", "carer", "goals", "eater", "treat", "eared", "adder", "dared", "dread",
         "corns", "fends", "alive", "comer", "crags", "metro", "duals", "fatso", "bytes", "exams", "bursa", "drags",
         "coils", "calve", "clave", "cruel", "solid", "force", "hopes", "brave", "ruled", "amine", "anime", "argue",
         "auger", "belay", "crits", "faxes", "clots", "colts", "beach", "bathe", "clods", "colds", "amble", "blame",
         "racks", "ashes", "dolts", "fresh", "goats", "stark", "sperm", "darks", "meant", "amend", "angel", "angle",
         "named", "homes", "trail", "trial", "fazes", "fable", "above", "ergot", "apses", "labor", "basin", "waves",
         "acorn", "disco", "caved", "cruet", "cuter", "cline", "crude", "cured", "adorn", "poems", "lined", "essay",
         "zones", "ankle", "bayed", "beady", "brine", "bands", "noble", "bikes", "seams", "exist", "exits", "bagel",
         "pulse", "boxes", "agent", "becks", "acrid", "carbo", "carob", "cobra", "abort", "craws", "clash", "board",
         "broad", "straw", "sized", "draws", "lower", "wines", "bleak", "brash", "exalt", "perks", "taken", "cells",
         "bento", "coati", "steel", "tells", "claps", "clasp", "naked", "scalp", "boned", "dells", "fuels", "setup",
         "upset", "gases", "beers", "badge", "dupes", "dashi", "faery", "clays", "braze", "prone", "frame", "lover",
         "spoke", "veins", "chats", "calms", "clams", "grape", "sadly", "cower", "brays", "chads", "sites", "aspic",
         "their", "tower", "wrote", "bidet", "debit", "hotel", "fails", "sides", "arena", "dower", "exact", "hired",
         "baked", "vents", "chert", "calfs", "cedes", "azide", "flats", "price", "fetus", "smoke", "filer", "flier",
         "rifle", "feuds", "tours", "pride", "daisy", "lions", "probe", "cecal", "crept", "helps", "cover", "ambos",
         "voter", "addle", "barer", "barre", "drove", "whose", "crime", "merit", "timer", "fiats", "ranks", "guest",
         "dimer", "model", "maker", "omega", "brags", "brome", "decry", "aunts", "facts", "urine", "boils", "aided",
         "coped", "coins", "fired", "fried", "icons", "sonic", "depot", "opted", "faker", "cribs", "dinos", "lacks",
         "blocs", "brits", "flesh", "shelf", "talks", "blots", "bolts", "under", "birds", "dribs", "dated", "dukes",
         "barks", "decoy", "comet", "comte", "clerk", "tiger", "abuts", "aleph", "dirge", "ridge", "boule", "daubs",
         "lodge", "cairn", "ounce", "train", "czars", "clued", "dinar", "drain", "eaves", "saves", "baron", "brute",
         "users", "warns", "types", "chefs", "stack", "moves", "short", "azure", "broke", "cutie", "blend", "began",
         "plans", "cheap", "peach", "dreck", "ample", "bloat", "maple", "arias", "claws", "corps", "crops", "braid",
         "ports", "sport", "canto", "drops", "bract", "crass", "stars", "start", "dozer", "menus", "owner", "hands",
         "polar", "story", "pains", "cobia", "corms", "bless", "bells", "blebs", "biota", "storm", "oasis", "dorms",
         "waist", "scene", "teens", "tents", "dicta", "flans", "pants", "dense", "needs", "sends", "chafe", "curls",
         "royal", "blaze", "liver", "flame", "spike", "toast", "amped", "frost", "moral", "argus", "chile", "sugar",
         "dosas", "dados", "write", "towel", "expos", "weird", "wider", "wired", "baths", "dowel", "balms", "antsy",
         "bower", "nasty", "value", "corer", "sandy", "grave", "welsh", "retro", "copra", "erode", "order", "beryl",
         "damns", "lemon", "baize", "beets", "beset", "bests", "berth", "divas", "olive", "sheer", "entry", "sharp",
         "dykes", "clove", "crust", "finer", "awoke", "felon", "carom", "curds", "macro", "diver", "drive", "label",
         "babel", "famed", "loved", "ethic", "clime", "yield", "peers", "press", "chide", "cowed", "gains", "rogue",
         "eaten", "boche", "image", "chews", "corks", "rocks", "shoes", "ultra", "cagey", "doyen", "dorks", "dural",
         "angst", "reign", "voice", "demon", "derby", "filet", "scout", "spray", "field", "filed", "video", "axils",
         "brief", "fiber", "fibre", "flake", "uncle", "poses", "whale", "swept", "bison", "cleft", "covet", "often",
         "biome", "curia", "balks", "delft", "abate", "betta", "dicey", "voted", "axons", "cargo", "eases", "asses",
         "cakey", "deity", "argot", "snack", "aloud", "doula", "tanks", "horns", "bonds", "fakie", "globe", "unite",
         "paper", "bairn", "brain", "fetid", "blued", "croak", "farms", "audio", "faked", "wheat", "grasp", "crows",
         "dunce", "enoki", "shirt", "tuned", "worst", "backs", "liked", "sword", "words", "brand", "holds", "biker",
         "bogie", "shark", "bloke", "extol", "token", "boxer", "norms", "crisp", "fives", "quest", "alias", "alums",
         "issue", "strip", "trips", "actin", "antic", "grams", "plots", "drips", "canid", "parks", "spark", "bawls",
         "bacon", "jokes", "class", "calls", "baton", "lasts", "atlas", "cubed", "wants", "debut", "equal", "salad",
         "dudes", "dawns", "brass", "barbs", "oxide", "gives", "creel", "girls", "marks", "apron", "elder", "codex",
         "erupt", "agree", "eager", "detox", "drupe", "chair", "ruins", "first", "ahold", "blurs", "basso", "abhor",
         "poker", "casts", "below", "bowel", "chart", "elbow", "moist", "novel", "turns", "crier", "cello", "chard",
         "roman", "chine", "niche", "coupe", "flair", "eider", "direr", "drier", "rider", "dried", "demur", "doled",
         "beamy", "dwelt", "endow", "maybe", "owned", "rapid", "borer", "belch", "ejido", "ewers", "sewer", "clogs",
         "coifs", "erect", "heels", "shell", "lunar", "mixes", "creed", "bolus", "deter", "cults", "dairy", "diary",
         "devil", "lived", "boyar", "curbs", "sound", "twice", "burst", "sleep", "spell", "patio", "diode", "fixes",
         "coven", "locks", "bowed", "skirt", "focal", "nexus", "cooed", "codec", "coded", "argon", "organ", "serve",
         "verse", "aloft", "float", "doted", "boney", "ebony", "adopt", "cutis", "denim", "urged", "chess", "plays",
         "bangs", "sheet", "these", "bicep", "chaps", "smell", "craft", "flash", "paths", "lamps", "psalm", "pipes",
         "bouts", "power", "broil", "hours", "views", "wives", "civet", "draft", "evict", "feint", "expat", "ducts",
         "fiend", "fined", "intro", "today", "reply", "cigar", "specs", "aware", "feels", "flees", "steep", "pests",
         "steps", "fells", "hover", "flaps", "deeps", "speed", "rolls", "chasm", "binds", "maths", "banks", "stock",
         "bilge", "docks", "ducal", "adult", "apple", "asura", "auras", "flays", "prove", "deign", "meets", "stems",
         "camps", "befit", "shaft", "yours", "boric", "cloak", "epoch", "stamp", "deems", "fiefs", "fifes", "orbit",
         "prime", "damps", "cowls", "hoped", "wrist", "haven", "alley", "nasal", "faxed", "flyer", "ensue", "cache",
         "bland", "feces", "brows", "track", "fetes", "fests", "audit", "cross", "crocs", "ahead", "feeds", "sorts",
         "roots", "about", "dross", "doors", "chemo", "clips", "split", "ducat", "siege", "sleek", "peace", "apace",
         "fazed", "mercy", "fella", "cabin", "crawl", "beaux", "fiery", "drawl", "volts", "dopey", "noisy", "balsa",
         "basal", "balls", "flags", "tempo", "edges", "buses", "chits", "scans", "ranch", "inner", "dozen", "sigma",
         "brims", "fauns", "skies", "matte", "biked", "rival", "viral", "eagle", "edema", "algae", "legal", "rebel",
         "grove", "amour", "rings", "boxed", "enter", "curve", "packs", "basis", "flask", "dekes", "desks", "rainy",
         "aorta", "faded", "ancho", "chute", "ceili", "ardor", "fonts", "elite", "title", "buyer", "burns", "piano",
         "elide", "batts", "brier", "bribe", "harsh", "ditsy", "grief", "wells", "elect", "midst", "combs", "vegan",
         "capon", "choke", "vocal", "donee", "brigs", "agate", "blogs", "beret", "bench", "adage", "units", "breed",
         "bravo", "claim", "daily", "amino", "amnio", "clubs", "bonus", "bosun", "dongs", "whole", "calif", "diced",
         "grain", "along", "ackee", "elves", "bocce", "brisk", "curio", "avoid", "glued", "sweet", "booed", "boded",
         "conks", "threw", "flaws", "knots", "weeds", "avows", "grant", "court", "grand", "urban", "bendy", "colin",
         "admit", "crush", "phone", "hurts", "guide", "beeps", "forms", "stick", "conga", "crank", "bronc", "drank",
         "ethyl", "honey", "usual", "grass", "begin", "being", "binge", "hangs", "daunt", "south", "soils", "apnea",
         "leave", "valve", "ruler", "walks", "offer", "blows", "bowls", "genes", "mayor", "cools", "borax", "chins",
         "slots", "stool", "tools", "depth", "coups", "hints", "towns", "beefs", "drums", "squad", "dolls", "chime",
         "downs", "ferny", "boors", "enema", "blips", "index", "fiver", "money", "chief", "fiche", "knees", "thief",
         "cisco", "brawl", "choir", "movie", "altar", "evade", "covey", "linen", "drawn", "fetch", "limbs", "abbey",
         "plain", "costs", "fangs", "torch", "chord", "focus", "glove", "moved", "quote", "stood", "aioli", "drugs",
         "minds", "eight", "plant", "circa", "local", "execs", "trait", "chain", "china", "allot", "atoll", "total",
         "vague", "texts", "bluey", "deify", "edify", "arbor", "finds", "sizes", "micro", "belie", "carat", "halls",
         "shall", "tract", "bible", "bitsy", "chant", "links", "panic", "cavil", "final", "fraud", "paint", "indie",
         "dined", "vital", "worms", "celeb", "betel", "valid", "sells", "prize", "bleed", "mixer", "fiord", "dings",
         "bogey", "habit", "bongs", "cornu", "chops", "cotta", "croft", "duvet", "round", "while", "heavy", "admin",
         "align", "batch", "bunts", "fixer", "guard", "badly", "baldy", "bunds", "fleck", "small", "candy", "corgi",
         "hello", "bided", "bugle", "bulge", "clang", "finca", "dinks", "faint", "kinds", "evens", "seven", "bonks",
         "clout", "gland", "cheer", "davit", "grows", "tests", "ether", "there", "three", "cloud", "could", "pasta",
         "falls", "seeds", "deeds", "fawns", "turbo", "elope", "ambit", "amiss", "comps", "firms", "brush", "white",
         "creep", "crepe", "dazed", "grips", "acing", "exult", "clank", "stays", "tasty", "giant", "eyrie", "vapor",
         "dyads", "charm", "exurb", "march", "blond", "works", "joins", "virus", "glass", "guess", "women", "budge",
         "debug", "burps", "wiped", "party", "creme", "dryer", "ghost", "meter", "cramp", "fasts", "staff", "axion",
         "femur", "chive", "doped", "lists", "still", "kinda", "black", "twins", "dills", "world", "winds", "sheep",
         "bolls", "blobs", "envoy", "added", "risky", "defer", "favor", "fairy", "north", "shock", "atopy", "emote",
         "campo", "domed", "modem", "music", "buoys", "batik", "elute", "culpa", "juice", "egret", "greet", "folks",
         "elude", "gauge", "edger", "brawn", "dusty", "study", "cloth", "drily", "discs", "crowd", "ficus", "minor",
         "quiet", "quite", "casks", "third", "broch", "tasks", "pilot", "boost", "boots", "broth", "corny", "crony",
         "burgs", "anvil", "anion", "eying", "creek", "briar", "messy", "pixel", "dodge", "walls", "props", "canon",
         "caput", "front", "deuce", "donna", "fault", "etude", "chows", "bogus", "dirty", "dhows", "feign", "optic",
         "topic", "sorry", "bayou", "annex", "rooms", "dogma", "fakir", "incur", "chips", "cacti", "attic", "divan",
         "flows", "sense", "datum", "blurt", "drift", "abbot", "adobo", "watts", "wrath", "knife", "stuck", "logic",
         "ducks", "lever", "dishy", "keeps", "bandy", "newly", "error", "begun", "major", "caulk", "visas", "bruit",
         "spicy", "mixed", "souls", "gross", "burka", "count", "shift", "enjoy", "films", "blush", "donut", "river",
         "trust", "agape", "aroma", "armor", "fixed", "blind", "abyss", "bassy", "trick", "blank", "aphid", "cycle",
         "aural", "rural", "aptly", "sight", "patch", "beery", "berry", "clamp", "piece", "dwarf", "ember", "doubt",
         "minus", "bebop", "chubs", "aglow", "bliss", "bills", "genre", "green", "yacht", "fleet", "color", "crown",
         "croup", "match", "dolor", "drool", "droll", "flour", "agora", "aggro", "barmy", "drown", "lungs", "faith",
         "proud", "boons", "boson", "bombe", "angry", "ennui", "picks", "print", "funds", "amity", "chino", "tumor",
         "busty", "canal", "droid", "child", "using", "birch", "chalk", "birth", "gifts", "vault", "shown", "feted",
         "basks", "notch", "agony", "banjo", "given", "point", "among", "syrup", "alibi", "album", "aunty", "loops",
         "pools", "polls", "exert", "cabal", "bulks", "butte", "ditch", "hawks", "magic", "alkyd", "botch", "shiny",
         "cohos", "dunks", "hosts", "shots", "shoot", "diked", "ebook", "bipod", "until", "newer", "renew", "weeks",
         "upper", "query", "bruin", "grind", "flack", "divot", "arrow", "coops", "scoop", "porch", "aloha", "posts",
         "spots", "stops", "crazy", "axiom", "vodka", "rally", "brunt", "bucks", "burnt", "stats", "alarm", "eerie",
         "dozed", "empty", "dwell", "built", "dingo", "doing", "drink", "nerve", "never", "build", "gloss", "dooms",
         "logos", "hence", "swift", "apart", "tenth", "erred", "alloy", "culls", "loyal", "coach", "bound", "watch",
         "dulls", "forth", "bleep", "woman", "burrs", "burbs", "foods", "doffs", "carry", "awake", "brick", "block",
         "dryad", "bigot", "delve", "risks", "handy", "agave", "looks", "knows", "drama", "aloof", "belly", "cubit",
         "beech", "glory", "suits", "goods", "curly", "truly", "forty", "comma", "clown", "toxic", "dived", "dusts",
         "drill", "epoxy", "balmy", "burqa", "wagon", "fence", "brown", "croon", "sixth", "socks", "cooks", "cocks",
         "donor", "afoot", "touch", "colic", "fancy", "seems", "embed", "finks", "hills", "banal", "amaze", "crack",
         "briny", "fruit", "exile", "robot", "thank", "chewy", "corky", "rocky", "brood", "dorky", "beige", "pills",
         "excel", "razor", "kings", "emery", "merry", "flank", "beget", "spoon", "cushy", "idiot", "ditto", "silly",
         "bitch", "climb", "graph", "chums", "balky", "calyx", "throw", "worth", "bunks", "asana", "annas", "ferry",
         "woods", "cling", "weigh", "bring", "chirp", "allow", "fills", "equip", "seeks", "dumps", "plugs", "blunt",
         "truck", "award", "clink", "merge", "booze", "dowry", "elven", "chugs", "bossy", "boyos", "bingo", "brink",
         "swing", "wings", "cysts", "masks", "auxin", "booms", "bosom", "bombs", "eejit", "duped", "chica", "crimp",
         "fists", "songs", "stiff", "clomp", "bylaw", "laugh", "eject", "bulls", "bulbs", "crypt", "annoy", "churn",
         "awash", "catch", "bundt", "cecum", "dacha", "kills", "skill", "bevel", "flail", "event", "where", "dweeb",
         "right", "annul", "would", "ceded", "fatal", "occur", "adapt", "trout", "tutor", "burly", "judge", "aught",
         "busts", "butts", "catty", "bawdy", "blown", "greek", "cycad", "caddy", "colon", "kicks", "dusky", "facia",
         "joint", "disks", "dhikr", "boron", "pound", "books", "bulla", "spurs", "myths", "fishy", "conic", "dutch",
         "mount", "cheep", "clack", "crumb", "fewer", "cupid", "fluid", "aquas", "blood", "every", "codon", "condo",
         "found", "favas", "amply", "theme", "champ", "guilt", "guild", "humor", "twist", "dumbo", "fever", "bushy",
         "petty", "trunk", "bezel", "theft", "drunk", "dodos", "bling", "prior", "bumps", "campy", "elegy", "floor",
         "human", "finis", "visit", "droop", "awful", "hedge", "bhaji", "chana", "rough", "blink", "radar", "avail",
         "villa", "axing", "fjord", "belle", "motor", "month", "await", "filch", "forum", "pitch", "signs", "grown",
         "wrong", "filth", "cheek", "check", "group", "ended", "cacao", "cocoa", "lunch", "shops", "anima", "augur",
         "canny", "inbox", "dimly", "evoke", "dandy", "wheel", "skins", "atman", "light", "adman", "fitly", "ebbed",
         "druid", "blitz", "wound", "burro", "flaky", "cabby", "batty", "input", "assay", "again", "aging", "baddy",
         "amass", "crook", "crock", "pulls", "sushi", "unity", "cumin", "axial", "butch", "bozos", "thick", "penny",
         "clung", "refer", "exude", "marry", "honor", "cusps", "hooks", "shook", "flick", "enemy", "clunk", "aback",
         "pouch", "dicky", "boobs", "dryly", "cuffs", "stuff", "pinch", "trump", "duffs", "flown", "youth", "naval",
         "chico", "venue", "witch", "mouth", "calla", "skull", "cuppa", "width", "cyclo", "coyly", "expel", "shows",
         "beefy", "dolly", "downy", "grill", "broom", "avian", "blimp", "ships", "coopt", "finch", "blurb", "flood",
         "comic", "quilt", "sucks", "cough", "ought", "tough", "dusks", "dough", "dotty", "union", "lying", "ching",
         "alpha", "night", "thing", "rigid", "bijou", "jelly", "bunch", "blini", "fling", "crick", "clock", "think",
         "brook", "bight", "highs", "apply", "teeth", "melee", "dingy", "dying", "chomp", "sunny", "bindi", "dinky",
         "emcee", "queen", "chaff", "chill", "chili", "ninja", "nylon", "conch", "clump", "buffs", "curvy", "bloop",
         "fatty", "widow", "vinyl", "daffy", "ditzy", "duchy", "comfy", "edged", "egged", "proxy", "dilly", "canna",
         "alkyl", "limit", "lobby", "fauna", "booth", "bloom", "cliff", "jewel", "bimbo", "bough", "ditty", "young",
         "booty", "going", "rugby", "combo", "congo", "lucky", "promo", "click", "array", "level", "tweet", "knock",
         "proof", "cubic", "digit", "imply", "chimp", "truth", "ducky", "punch", "fatwa", "couch", "filmy", "fanny",
         "curry", "cinch", "ninth", "durum", "might", "civil", "cocci", "duomo", "billy", "jumps", "cynic", "fight",
         "thumb", "plaza", "bonny", "baggy", "pumps", "pizza", "bitty", "chunk", "worry", "holly", "biddy", "affix",
         "bongo", "photo", "bulky", "allay", "allyl", "compo", "pupil", "byway", "buxom", "daddy", "algal", "doomy",
         "juicy", "dully", "onion", "chock", "cutup", "bubba", "happy", "dodgy", "doggy", "cuddy", "swiss", "cocky",
         "cluck", "quick", "femme", "chump", "dowdy", "hobby", "filly", "dippy", "dumpy", "fifth", "boppy", "abaya",
         "boomy", "tight", "thigh", "fifty", "bully", "chick", "bluff", "boggy", "cubby", "buddy", "babka", "queue",
         "which", "doozy", "tooth", "commo", "bumpy", "civvy", "divvy", "known", "bunny", "dizzy", "boozy", "fully",
         "chuff", "gamma", "dummy", "booby", "bobby", "boffo", "chuck", "funny", "civic", "vivid", "buggy", "fizzy",
         "buzzy", "puppy", "yummy"]

best_letters = ["e", "s", "a", "r", "o", "l", "i", "c", "t", "d", "n", "b", "u", "h", "p"]


def get_score(letter_set):
    score = len(letter_set)
    if 'x' in letter_set:
        score = score + 1
    if 'w' in letter_set:
        score = score + 1
    if 'v' in letter_set:
        score = score + 1
    return score


word_char_list = list(map(lambda w: set(w), words))

best_score = 0
best_words = ""
for wi in word_char_list:
    letters_i = wi
    words_j = list(filter(lambda w: len(set(w).intersection(letters_i)) == 0, words))
    for wj in words_j:
        letters_j = letters_i.union(wj)
        if len(letters_j) < 10:
            continue
        words_k = list(filter(lambda w: len(set(w).intersection(letters_j)) == 0, words_j))
        for wk in words_k:
            letters_k = letters_j.union(wk)
            if len(letters_k) < 15:
                continue
            words_l = list(filter(lambda w: len(set(w).intersection(letters_k)) == 0, words_k))
            for wl in words_l:
                letters_l = letters_k.union(wl)
                if len(letters_k) < 20:
                    continue
                words_m = list(filter(lambda w: len(set(w).intersection(letters_l)) == 0, words_l))
                for wm in words_m:
                    letters_m = letters_l.union(wm)
                    new_score = get_score(letters_m)
                    if best_score <= new_score:
                        best_score = new_score
                        best_words = (wi, wj, wk, wl, wm)
                        print(best_words, best_score, sorted(letters_m))
